# Dependencies
markdown:         rdiscount
highlighter:         true

# Permalinks
permalink:        pretty

# Server
host:             0.0.0.0
port:             9001
baseurl:          /
encoding:         UTF-8